/**
 * Auto-generated maze constants
 * Generated at: 2026-07-25T12:35:46.636Z
 * Source: maze-config.json
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: just generate-constants
 */

/** Maximum total cells in a maze (width * height) */
export const MAX_MAZE_CELLS = 3000;

/** Maximum packed bytes for cell data (2 cells per byte) */
export const MAX_PACKED_BYTES = 1500;

/** Maximum number of moves in a solution */
export const MAX_MOVES = 1000;

/**
 * Number of public inputs for ZK proof verification.
 * = [maze_hash, move_count] under the hash-as-public-input architecture.
 */
export const PUBLIC_INPUTS_LENGTH = 3;

/** Header bytes for the canonical maze layout (10 big-endian u16s). */
export const LAYOUT_HEADER_BYTES = 20;

/** Total bytes of the canonical layout (header + zero-padded packed cells). */
export const LAYOUT_TOTAL_BYTES = 1520;
