/**
 * Auto-generated from maze_prover/target/maze_prover.json
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: just generate-prover-input-types
 *
 * This file is the source of truth for the TypeScript shape of the prover
 * input. `zkSerialize.ts` aliases `ProverInput = ProverInputCircuit`, so
 * any drift between the Noir circuit's main() signature and the object
 * returned by `generateProverInput` is caught at TypeScript compile time
 * (rather than at proof time, where nargo's "input not found" error is
 * cryptic — see retro Appendix C, bead ma-7qm).
 *
 * Sibling to `scripts/check-abi-drift.js` (ma-3xv): that gate validates the
 * *count* of `pub` params; this one pins the *field shape*.
 */

/* eslint-disable */

/**
 * Prover input shape, generated from the circuit ABI.
 *
 * Field order matches the circuit's main() parameter list. Noir's InputMap
 * is name-keyed at the witness layer, so the order in this object is
 * irrelevant to proof validity — but matching it keeps diffs minimal when
 * the circuit is extended.
 */
export interface ProverInputCircuit {
  /** public · Field (32-byte BN254 scalar) */
  maze_hash: `0x${string}`;
  /** public · u32 */
  move_count: number;
  /** public · Field (32-byte BN254 scalar) */
  sender: `0x${string}`;
  /** private · u16 */
  width: number;
  /** private · u16 */
  height: number;
  /** private · u16 */
  start_x: number;
  /** private · u16 */
  start_y: number;
  /** private · u16 */
  robe_x: number;
  /** private · u16 */
  robe_y: number;
  /** private · u16 */
  scepter_x: number;
  /** private · u16 */
  scepter_y: number;
  /** private · u16 */
  goal_x: number;
  /** private · u16 */
  goal_y: number;
  /** private · [u8; 1500] */
  packed_cells: number[];
  /** private · [u8; 1000] */
  moves: number[];
}

/**
 * Runtime-iterable list of every key in {@link ProverInputCircuit}, in
 * circuit ABI declaration order. Useful for asserting at runtime that an
 * input object has every required field populated (e.g. tests, debug logs).
 */
export const PROVER_INPUT_KEYS = [
  'maze_hash',
  'move_count',
  'sender',
  'width',
  'height',
  'start_x',
  'start_y',
  'robe_x',
  'robe_y',
  'scepter_x',
  'scepter_y',
  'goal_x',
  'goal_y',
  'packed_cells',
  'moves',
] as const satisfies ReadonlyArray<keyof ProverInputCircuit>;

/**
 * Subset of {@link PROVER_INPUT_KEYS} marked `pub` in the circuit (i.e.
 * exposed on-chain via the verifier). Keep aligned with
 * `MazeConstants.PUBLIC_INPUTS_LENGTH` — `scripts/check-abi-drift.js`
 * enforces that count.
 */
export const PROVER_PUBLIC_INPUT_KEYS = [
  'maze_hash',
  'move_count',
  'sender',
] as const satisfies ReadonlyArray<keyof ProverInputCircuit>;
